source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

target 'VRFoundationToolkitTests', :exclusive => true do
  pod "VRFoundationToolkit", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
